services:
  - type: web
    name: astrology-research-database
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_global:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true 